#!/bin/sh

set -e
set -x

GENTLE=../gentle-97/gentle/gentle
GRTS=../gentle-97/gentle/grts.o
REFLEX=../gentle-97/reflex/reflex
LIB=../gentle-97/lib
LEX=lex
YACC=yacc
CC=cc
PLIK=grama

$GENTLE $PLIK.g

$REFLEX

$LEX gen.l

$YACC -v gen.y

$CC -o $PLIK \
   $PLIK.c \
   lex.yy.c \
   y.tab.c \
   $LIB/errmsg.o \
   $LIB/main.o \
   $LIB/idents.o \
   $GRTS

